### PR TITLE
feat: there are several months on the calendar

### PR DESCRIPTION
**Pull request by vf1**
BREAKING CHANGE: calendar data type

image

### CODE REVIEW

**Comment by its-danny** [comment]
@vf1 thanks! the reason i hadn't yet added this is because i don't like the idea of returning something not `Date`. trying to stick with how date-fns works, returning native types whenever possible.

i was previously thinking of instead of returning `calendar: Date[][]` we can instead return `calendars`, which is just an array of `Date[][]`. to get the first day of the month, you can just use `date-fns`. that way we don't need `CalendarMonth`.

you'd just render `calendars.map` and it works whether you only have 1 or 30. so the change required after upgrading is just changing `calendar` to plural and using `map`. however you're rendering it wouldn't need to be changed.

any thoughts?

**Comment by vf1** [comment]
@its-danny actually the first edition was with ```calendar: Date[][][]```, but IMHO it is not very readable when maping to components.  A version ```calendar: Date[][][] | Date[][]``` is confusing too. I would prefer to use ```months``` instead of ```calendars```: ```months.map(month => month.weeks.map(week =>...``` The month typically contains days, but with clarification ```weeks``` it looks good.

**Comment by its-danny** [comment]
@vf1 that makes sense. can you update it to just be `months` instead of calendar, then? also `yarn build-docs` to update the ts docs.

`firstDay` seems unnecessary still since you can just use [isFirstDayOfMonth](https://date-fns.org/v2.23.0/docs/isFirstDayOfMonth) from date-fns. would like to let that library handle as much as possible. any reason we'd want to not do that? it'd still be `Date[][][]` but called `months` it'd maybe be more clear?

also i can just do it myself, i don't have many people open PRs on my stuff so not sure if it's more polite to ask you to do it or me to do it lol. feel free to ask me to if you don't feel like it, tho.

**Comment by vf1** [comment]
> `firstDay` seems unnecessary still since you can just use [isFirstDayOfMonth](https://date-fns.org/v2.23.0/docs/isFirstDayOfMonth) from date-fns.

Do you mean search for first day in calendar/months?

> would like to let that library handle as much as possible. any reason we'd want to not do that? it'd still be `Date[][][]` but called `months` it'd maybe be more clear?

The `Date[][][]` is not self descriptive for me. This could of course be the solution, but I prefer data structure that can be read w/o docs. This is a purely personal opinion. I am not sure that it will be correct decision in this case.

> also i can just do it myself, i don't have many people open PRs on my stuff so not sure if it's more polite to ask you to do it or me to do it lol. feel free to ask me to if you don't feel like it, tho.

@its-danny think I need even more specific version for mine project. So I will try to change your lib without regard to compatibility, and then try to find general purpose features to come back with new PR.

**Pull request closed without merging**
