### PR TITLE
Issue #486 Fix infinite loop in useLayoutEffect

### PR DESCRIPTION
**Pull request by riordanpawley**
Fix for issue #486

### CODE REVIEW

**Review by its-danny — APPROVED** [review]

**Comment by its-danny** [comment]
@riordanpawley gonna be honest, i don't think i ever clicked more than 2 when testing it out to throw some examples up there lol. appreciate the fix!

**Comment by its-danny** [comment]
@riordanpawley do you mind changing the commit message to:

```
docs(examples): fix infinite loop in useLayoutEffect

closes #486
```

**Comment by riordanpawley** [comment]
> @riordanpawley do you mind changing the commit message to:
> 
> ```
> docs(examples): fix infinite loop in useLayoutEffect
> 
> closes #486
> ```

Sure thing :)

**Comment by its-danny** [comment]
@riordanpawley thanks!

**Pull request merged**
